/**
 * Performing unit tests on the User model
 *
 * Random passwords are generated by:
 * @link https://www.avast.com/random-password-generator#pc
 *
 */
const User = require("../../src/models/user.model");
const validationErrorMessages = require("../../src/resources/validationErrorMessages");

describe("User model tests:", () => {
  describe("valid username", () => {
    it("should pass validation", () => {
      const user = new User({
        username: "myNewUserName",
      });

      const err = user.validateSync();

      expect(err).toBeUndefined();
    });
  });

  describe("invalid username", () => {
    const usernameInvalidCases = [
      [
        "should not pass validation -> username empty",
        new User({
          username: "",
        }),
      ],
      [
        "should not pass validation -> username too short",
        new User({
          username: "ab",
        }),
      ],
    ];

    usernameInvalidCases.forEach(([testName, input]) => {
      it(testName, () => {
        const user = input;
        const err = user.validateSync();
        expect(err).toBeDefined();
        expect(err.errors.username).toBeDefined();
        expect(err.errors.username.message).toBe(
          validationErrorMessages.USERNAME_MIN_LENGTH
        );
      });
    });

    it("should not pass validation -> username too long", () => {
      const user = new User({
        username: "ThisIsMyUsernameAsAnAppUser",
      });
      const err = user.validateSync();
      expect(err).toBeDefined();
      expect(err.errors.username).toBeDefined();
      expect(err.errors.username.message).toBe(
        validationErrorMessages.USERNAME_MAX_LENGTH
      );
    });
  });

  describe("valid email", () => {
    it("should pass validation", () => {
      const user = new User({
        email: "sokey72413@lofiey.com",
      });

      const err = user.validateSync();
      expect(err).toBeUndefined();
    });
  });

  describe("invalid email", () => {
    const emailInvalidCases = [
      [
        "should not pass validation -> no prefix",
        new User({ email: "@mail.com" }),
      ],
      [
        "should not pass validation -> no @",
        new User({ email: "randommailcom" }),
      ],
      [
        "should not pass validation-> no domain name",
        new User({ email: "random@.com" }),
      ],
      [
        "should not pass validation -> no .",
        new User({ email: "random@mailcom" }),
      ],
      [
        "should not pass validation -> not top level domain",
        new User({ email: "random@mail." }),
      ],
    ];

    emailInvalidCases.forEach(([testName, input]) => {
      it(testName, () => {
        const user = input;
        const err = user.validateSync();
        expect(err).toBeDefined();
        expect(err.errors.email).toBeDefined();
        expect(err.errors.email.message).toBe(
          validationErrorMessages.EMAIL_INVALID
        );
      });
    });
  });

  describe("valid password", () => {
    it("should pass validation", () => {
      const user = new User({
        password: "{3&LGNaC4+Okhzh",
      });

      const err = user.validateSync();
      expect(err).toBeUndefined();
    });
  });

  describe("invalid password", () => {
    const passwordInvalidCases = [
      [
        "should not pass validation -> no lowercase characters",
        new User({ password: "MPZVVPTZHGUSJJY" }),
      ],
      [
        "should not pass validation -> no uppercase characters",
        new User({ password: "lb,$rj469pr11v;" }),
      ],
      [
        "should not pass validation -> no numbers",
        new User({ password: "+c&uYXi~nVbUNBq" }),
      ],
      [
        "should not pass validation -> no special characters",
        new User({ password: "eOJw0yjymc1zcUP" }),
      ],
    ];

    passwordInvalidCases.forEach(([testName, input]) => {
      it(testName, () => {
        const user = input;
        const err = user.validateSync();
        expect(err).toBeDefined();
        expect(err.errors.password).toBeDefined();
        expect(err.errors.password.message).toBe(
          validationErrorMessages.PASSWORD_MUST_HAVE_CHARACTERS
        );
      });
    });
  });
});
